//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangPhanCong
    {
        public string HoTen { get; set; }
        public System.TimeSpan GioBatDau { get; set; }
        public System.TimeSpan GioKetThuc { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<System.DateTime> GioDen { get; set; }
        public Nullable<System.DateTime> GioVe { get; set; }
        public int MaNV { get; set; }
        public int MaCa { get; set; }
        public int MaLichLam { get; set; }
        public Nullable<bool> CoMat { get; set; }
    }
}
