//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.DetailBookings = new HashSet<DetailBooking>();
        }
    
        public int BookID { get; set; }
        public Nullable<int> MaKH { get; set; }
        public System.DateTime NgayDat { get; set; }
        public System.DateTime NgayDen { get; set; }
        public Nullable<System.DateTime> ThoiDiemKetThuc { get; set; }
        public string Loai { get; set; }
        public Nullable<decimal> TongTienGoc { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailBooking> DetailBookings { get; set; }
    }
}
