//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongThuc
    {
        public int MaMA { get; set; }
        public int MaNL { get; set; }
        public string GhiChu { get; set; }
        public string DonVi { get; set; }
        public Nullable<double> SoLuong { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
