//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int MaComBo { get; set; }
        public int MaMA { get; set; }
        public int id { get; set; }
    
        public virtual CTCombo CTCombo { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
