//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKhuyenMai
    {
        public int MaKM { get; set; }
        public int MaMA { get; set; }
        public Nullable<int> giatienkhuyenmai { get; set; }
        public Nullable<int> sl { get; set; }
    
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
