//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTNhapHang
    {
        public int MaNhapH { get; set; }
        public int MaNL { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> ThoiDiemNhap { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhapNL NhapNL { get; set; }
    }
}
