//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public int MaDG { get; set; }
        public Nullable<int> MaMA { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaNH { get; set; }
        public int DANHGIA1 { get; set; }
        public string NDDG { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
