//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailBooking()
        {
            this.MonAn_DetailBooking = new HashSet<MonAn_DetailBooking>();
        }
    
        public int DetaiBookingID { get; set; }
        public int BookID { get; set; }
        public int MaBan { get; set; }
        public Nullable<decimal> Gia { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual Booking Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonAn_DetailBooking> MonAn_DetailBooking { get; set; }
    }
}
