//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public int BookID { get; set; }
        public Nullable<int> MaNV { get; set; }
        public System.DateTime Ngaylap { get; set; }
        public int MaKM { get; set; }
        public Nullable<int> TongTien { get; set; }
        public int MaGiamGia { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
    }
}
