//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLamViec
    {
        public int MaLichLam { get; set; }
        public int MaNhanVien { get; set; }
        public System.DateTime Ngay { get; set; }
        public int MaCa { get; set; }
        public Nullable<System.DateTime> GioDen { get; set; }
        public Nullable<System.DateTime> GioVe { get; set; }
        public Nullable<bool> CoMat { get; set; }
    
        public virtual CaLamviec CaLamviec { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
