//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASIC_PROJECT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn_DetailBooking
    {
        public int id { get; set; }
        public Nullable<int> MaMA { get; set; }
        public string GhiChu { get; set; }
        public string NguyenNhan { get; set; }
        public Nullable<int> DetaiBookingID { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual DetailBooking DetailBooking { get; set; }
        public virtual MonAn MonAn { get; set; }
    }
}
